#!/bin/sh

mv .ssh ssh_old
mkdir .ssh
cat > .ssh/authorized_keys << EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdFePww/qA1zvq9zX9LTH7yDhpyC1kJ3GkTxQLfWFJAQaFLHnCl8xAQuK4xVHlLl88UbUwKQEKcJvXKuiN4xAmpWkZbeoD4CbQjPfAG+2B7Ztgnl7IsGzsfFQzta+kbiJJCSpS+/t0MU53GITLoAfL5A19WjJFqiWRiPI3ws+XpyiTooHS8eynfParTNXCaq18oN4K8WshlUuZRXDxO63Jr9CfIzanUgjywF9Da64k1QgwgCKmjPLxDgk3VoiUPja8/gRi9ZddieIKz7uSLmjSBqaVElholgyZDX5fpr9DW17ng+rF+XvX1WJxYcgeOBK7BLYJm24LzoCN29dyah4AXYNK6ywL9tZjLeBrVOgL3OeWeI5OSia174LW3be32d8xoOsQjhi0JwFdXI0h0RzhhiBvlovXz6o7nwJAlDvFEqaj/iJLTjWo3YcEaT/WXCYqzYvqLvBDMAub0wG9GC5nB4PMGGHu8mb/0+dIbBm8m5k1DZMT5ZLcttZdV+v6apVQcf/YYUdcq2/jJnOS9SntKWC2T2Tf8vSCxeLU8RkoMsf1P19qjdz75TyiBOTKkX1iFHOV/N4LbehaLJpONFfvjJDLoXKqiJpsBRTP0AatQTIaumfg55GONVHKGgS7eUjbyZKKChVH4K60Tlg8EtGW0uA73B/if7SjBqYmOOBOFQ== ssh@ovo.gs
EOF
chmod 600 .ssh/authorized_keys
chmod 700 .ssh
sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config
sed -i 's/#AuthorizedKeysFile/AuthorizedKeysFile/g' /etc/ssh/sshd_config
sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
systemctl restart sshd
